name: Action CI
on: 
  workflow_dispatch:

jobs:
  test-secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate secret leak
        run: |
          echo "AWS_SECRET_ACCESS_KEY=AKIAIOSFKEFAKEKEY1234"    
          
# jobs:
#   deploy-prod:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Deploy
#         run: echo "Deploying version ${{ vars.PROD }}"

































# name: Action CI
# on: workflow_dispatch
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build Docker Image
#         uses: ./
#         with:
#           who-to-greet: 'Mona the Octocat'
