name: VariableDemo

on: [push]

env:
  user_name: "Chaminda"
  demo_name: "Variable Demo"

jobs:
  VariableUsageJob:
    runs-on: ubuntu-latest
    steps:
      - name: Using Workflow Variables
        run: |
          echo "Hello, $user_name!"
          echo "Welcome to $demo_name!!!"



# name: .NET Core

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout GitHub Actions
#         uses: actions/checkout@v5

#       - name: Setup .NET Core
#         uses: actions/setup-dotnet@v5
#         with:
#           dotnet-version: 3.1.301

#       - name: Install dependencies
#         run: dotnet restore

#       - name: Build
#         run: dotnet build --configuration Release --no-restore

#       - name: Test
#         run: dotnet test --no-restore --verbosity normal

#       - name: Publish
#         run: dotnet publish -c Release -o dotnetcorewebapp

#       - name: Upload Artifacts
#         uses: actions/upload-artifact@v4
#         with:
#           name: my-artifact
#           path: ./dotnetcorewebapp
















# name: Action CI
# on: 
#   workflow_dispatch:

# jobs:
#   test-secret-scan:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Simulate secret leak
#         run: |
#           echo "AWS_SECRET_ACCESS_KEY=AKIAIOSFKEFAKEKEY1234"    

# jobs:
#   deploy-prod:
#     runs-on: ubuntu-latest
#     environment: production
#     steps:
#       - name: Deploy
#         run: echo "Deploying version ${{ vars.PROD }}"

































# name: Action CI
# on: workflow_dispatch
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Build Docker Image
#         uses: ./
#         with:
#           who-to-greet: 'Mona the Octocat'
